### ISSUE TITLE
portals break rendering on mekanism piping + other mod rendered items

### ISSUE THREAD

**Issue by wakkytabbaky** [qouteall/ImmersivePortalsModForForge#49] opened 2020-03-10 08:38 UTC
immersive-portals-0.4(for mc 1.15 with forge)
Mekanism-1.15.2-9.9.14.406

using immersive portals and mekanism creates a rendering bug for item pipes etc

https://imgur.com/a/uN48Rx9

the mekanism stuff still works fine its just rendering which is broken , the rendering issue only happens when you leave render distance / chunk the item pipes are in when there is a portal nearby. confirmed to be immersive portals breaking the rendering so thought id post it here instead of the mekanism github

client log with errors https://pastebin.com/261cXQva

**Comment by qouteall** [comment] 2020-03-10 09:00
The rendering issue may be correlated with Forge's model data system. Forge's model data system breaks when multiple client worlds are loaded. To solve that I need to rewrite forge model data system which is very hard.
The error in the log is caused by another issue. This issue may be caused by Mekanism mixing client and server when sending packets. Vanilla swallows all networking exceptions but this mod prints all network exceptions so this error is visible.

**Comment by tterrag1098** [comment] 2020-04-06 03:11
You are removing a *very important* check that makes sure the world being passed to clearCaches is the current client world. Doing this means that any time a different world is rendered the model data caches get wiped ENTIRELY. Why not just return early instead? Or better yet make it so your fake worlds never have model data stored at all?

https://github.com/qouteall/ImmersivePortalsModForForge/blob/1.15/src/main/java/com/qouteall/hiding_in_the_bushes/mixin/MixinForgeDimensionManager.java#L21

**Comment by qouteall** [comment] 2020-04-06 03:18
I don't know how the model data system works so I did some easy hack to avoid crashing. Can you explain in detail about how it should be? And is this related to DimensionManager?

**Comment by qouteall** [comment] 2020-04-06 11:09
@tterrag1098 I changed to return early so that rendering portal won't erase the player world's model data. But for example when the player goes to nether all model data in nether is missing. Is it appropriate to call ModelDataManager#requestModelDataRefresh for all tile entities when the player travels through portal? I will split it into multiple ticks to avoid lag.

**Comment by qouteall** [comment] 2020-04-07 08:34
This may be fixed in the latest version

**Comment by Splutty** [comment] 2020-04-15 16:05
It's not fixed, this still occurs with Immersive Portals 0.12 for MC 1.15.2.
Mekanism-1.15.2-9.9.20.412

https://i.imgur.com/4ok0NHj.png

**Comment by qouteall** [comment] 2020-04-16 05:06
If the remote pipe gets updated it will render improperly and this cannot be fixed.
If it renders improperly, put a block near it to rebuild the chunk and it will render normally

**Closed as completed by qouteall** 2020-04-16 05:06 UTC

**Comment by GrantGryczan** [comment] 2021-02-14 23:29
I'm having this issue as well on the latest version of both Immersive Portals and Mekanism as of the date of this post.
