### ISSUE TITLE
Server timeout on ocean temple encounter inside boats [1.15.2]

### ISSUE THREAD

**Issue by InsideBSI** [qouteall/ImmersivePortalsModForForge#78] opened 2020-04-19 16:35 UTC
So, the mod cause the server to enter an infinite timeout if you pass by an ocean temple inside of a boat.
This do not happens while flying in creative to the same place. And it's not happenning if I go there in creative before going by boat.
Going there by foot is fine as well
Here's two spark reports I made while boating to the same temple and the server timeouting (the sampling was set to be 5 minutes long): https://spark.lucko.me/#2UDTtmDy0Q https://spark.lucko.me/#eXnxVPDNIs (Set the mappings to MCP 1.15.2)

This whole issue disapear if I disable the mod

Modlist: https://i.imgur.com/VhrYhF5.jpg
Disabling the realistic first person view from advanced skin customizations changes nothing

Forge version tested: 31.1.46
Immersive portal version tested: 0.13 & 0.12

**Comment by InsideBSI** [comment] 2020-04-19 16:44
And I should add this: No errors in latest.log or debug.log

**Comment by InsideBSI** [comment] 2020-04-19 19:59
Seems like minecarts are impacted as well so I assume all vehicules are

**Comment by qouteall** [comment] 2020-04-20 00:32
It happens to be correlated with minecolonies and netherPortalSpread. It created a dead lock because when the server tries to load a chunk then triggered these mod's event handler and the mod tries to load the same chunk. 
You can try to uninstall nether portal spread mod because it probably won't work with this mod.

**Comment by qouteall** [comment] 2020-04-20 00:36
Maybe it's caused by this mod changing chunk loading sequence.

**Comment by qouteall** [comment] 2020-04-20 00:41
I called updateCameraPosition after a chunk loads and it caused the dead lock. It seems unnecessary and I removed it. Maybe this issue is fixed. It will be in the next version

**Comment by InsideBSI** [comment] 2020-04-20 11:46
Disabling the nether portal spread mod seems to have fixed the issue.
It wasn't working anyway so it doesn't change anyting for me but I'm kind of sad the two mods don't work together because it could have created a really nice effect.
Thanks for your time and have a nice day
Your mod is amazing by the way thanks for making it

**Closed as completed** 2020-04-21 12:01 UTC
