### ISSUE TITLE
End Portal not disappearing when frame is broken (1.14.4)

### ISSUE THREAD

**Issue by shredderslash** [qouteall/ImmersivePortalsModForForge#85] opened 2020-04-25 14:58 UTC
![2020-04-25_08 50 22](https://user-images.githubusercontent.com/8062717/80283134-c84d8880-86d2-11ea-8429-068c21f5b281.png)

**Comment by LoganDark** [comment] 2020-04-25 15:05
Duplicate of https://github.com/qouteall/ImmersivePortalsMod/issues/197

**Closed as completed** 2020-04-25 15:12 UTC
